### GET PRODUCTS
GET http://localhost:3000/api/products

### CREATE PRODUCT
POST http://localhost:3000/api/products
Content-Type: application/json

{
  "product": "Keyboard",
  "price": 1500,
  "stock": 5
}

### GET USERS
GET http://localhost:3000/api/users

### CREATE USER
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "John",
  "email": "john@email.com"
}

### CREATE ORDER
POST http://localhost:3000/api/orders
Content-Type: application/json

{
  "userId": 1,
  "items": [
    { "productId": 1, "quantity": 2 }
  ]
}

### GET ORDERS
GET http://localhost:3000/api/orders